#!/usr/bin/env node

var log = require('basic-log');

log('Hello!');
/*var tick = require('tick');

tick.start();

tick('this');
tick('that');

for (var i = 0; i < 10; i++) {
	tick('third');
}

tick.end();

*/

var tick = require('./');
tick.start();
tick('process', '1');
tick('process', '2');
tick.end();

//var myTick = new tick.Tick();

